# CONFIG FILE

message:
  error-claim: "§c[UniversalKey] Ce block a déjà était claim."
  valide-claim: "§c[UniversalKey] Votre block a bien était enrengistré."

item:
  # Name of item
  key: STICK

# AUTEUR : Harrysto#3533 / Discord
# PLUGIN COPYRIGHT @2022 AlexK