# CONFIG FILE

message:
  claim:
    error-claim: "§c[UniversalKey] Ce block a déjà était claim."
    valide-claim: "§c[UniversalKey] Votre block a bien était enrengistré."
  commands:
    key-lore: "§c[UniversalKey] Cette clé ne possède aucune serrure."
    syntax-error-key: "§c[UniversalKey] Il manque des arguments. /key <player> <name>."


item:
  # Name of item
  key: STICK

# AUTEUR : Harrysto#3533 / Discord
# PLUGIN COPYRIGHT @2022 AlexK