name: Claude
version: 1.0
author: Harrysto
main: fr.harrysto.claude.Main
commands:
  vkey:
    permission: vkey.use
    description: Commande de génération de clé.
  vkeyadmin:
    permission: vkeyadmin.use
    description: Commande administrateur du plugin.
  vkeyname:
    description: Définir le nom de votre clé.
    permission: vkeyname.use