name: Claude
version: 1.0
author: Harrysto
main: fr.harrysto.claude.main
commands:
  vkey:
    permission: vkey.claude.use
    description: Commandes du plugin
  vkeylist:
    permission: vkeylist.claude.use
    description: Voir toute les clé en circulation
  keymenu:
    description: Voir votre trouseau de clé