name: Claude
version: 1.0
author: Harrysto
main: fr.harrysto.claude.Main
commands:
  vkey:
    permission: vkey.use
    description: Générateur de clé '/vkey <name>'
  vkeyadmin:
    permission: vkeyadmin.use
    description: Commande admin de Valient Key
